### ISSUE TITLE
rapidocr-onnx-windows-x86 的版本号或许应该用 1.3.0

### ISSUE THREAD

**Issue by FlyInWind1** [MyMonsterCat/RapidOcr-Java#15]
这些jar里没有class，dll文件很少更新，每次更新后都会在 ~\.m2\repository 遗留下无用文件。
或许 rapidocr-onnx-windows-x86 的版本号应该用 1.3.0 而不是 0.0.6 ，1.3.0也就是 RapidOcr 官方发布的版本号。
如果 RapidOcr 官方不发布新版本, 1.3.0 这个版本号也就不用动了

**Comment by MyMonsterCat** [comment]
这个确实应该做出优化，不过版本号可能需要根据这个来定，因为依赖的是c++版本的，不是RapidOcr 官方python版本。
<img width="639" alt="image" src="https://github.com/MyMonsterCat/RapidOcr-Java/assets/33886291/a1f9e010-030b-414b-aff6-d06039cd5c5f">
感谢反馈，我会在晚些时候修改。

**Comment by MyMonsterCat** [comment]
不知道大佬有没有兴趣维护这个项目，可以的话我拉你为合作者。

**Comment by FlyInWind1** [comment]
可以啊。不过最近我的需求都做完之后，或许也就没啥新的想法了

**Comment by MyMonsterCat** [comment]
> 可以啊。不过最近我的需求都做完之后，或许也就没啥新的想法了

非常感谢你愿意加入并帮助维护这个项目！虽然这项目功能比较简单，但是你的参与仍然可以帮助改进现有的功能，优化代码质量，或者在未来探索新的方向（你提的好多问题是我在使用过程中没有遇到过的），同时我们也可以定期进行讨论，看看是否有任何潜在的改进点或新功能。
我已经邀请你了，记得点一下同意！
