### ISSUE TITLE
RapidOcr-Java关于centos7版本部署出现依赖报错问题

### ISSUE THREAD

**Issue by lilinzhi666** [MyMonsterCat/RapidOcr-Java#16]
请问可以出一期教程嘛

或者是能出一个兼容centos7的gcc环境兼容版本，因为升级各种原因报错而且非常耗时

请大佬出一期，一定可以火一把哈
支持大佬

**Comment by MyMonsterCat** [comment]
感谢使用，最近项目紧比较忙，后面有时间我写一下。

**Comment by MyMonsterCat** [comment]
简单写了一下，可以先当作参考[如何在CentOS7或其他低版本Linux系统上运行](https://github.com/MyMonsterCat/RapidOcr-Java/blob/main/docs/CentOS7.md)
