### ISSUE TITLE
linux环境执行报错

### ISSUE THREAD

**Issue by hongwazi** [MyMonsterCat/RapidOcr-Java#19]
![1](https://github.com/MyMonsterCat/RapidOcr-Java/assets/7822596/7a51f774-f82f-41b5-aa0f-4f44f4494763)

**Comment by FlyInWind1** [comment]
目前在windows上打包的话，只会带上windows的dll，没有linux的so。
建议手动在 pom.xml 加一个依赖
<dependency>
    <groupId>io.github.mymonstercat</groupId>
    <artifactId>rapidocr-onnx-linux-x86_64</artifactId>
    <version>${rapidocr.java.version}</version>
</dependency>

**Comment by hongwazi** [comment]
> 目前在windows上打包的话，只会带上windows的dll，没有linux的so。 建议手动在 pom.xml 加一个依赖 `rapidocr-onnx-linux-x86_64`

我把服务器的jar解压看了下，是有so的，我尝试手动新增依赖试试。

**Comment by hongwazi** [comment]
> > 目前在windows上打包的话，只会带上windows的dll，没有linux的so。 建议手动在 pom.xml 加一个依赖 `rapidocr-onnx-linux-x86_64`
> 
> 我把服务器的jar解压看了下，是有so的，我尝试手动新增依赖试试。

试了下，不太行。。。。so文件是存在的。

**Comment by FlyInWind1** [comment]
你是在 console 里找日志的而，还是 sl4j 的日志文件里面。
我刚刚在 RapidOcr-Java 的源码里面发现了 e.printStackTrace() 。。。
建议在 console 的日志里面看看，还有没有其他报错。

**Comment by hongwazi** [comment]
> 如果还是不行的话。建议写一个demo代码，还有jar包，可以复现这个问题的

今天在阿里云用docker，跑也是一样的错误，不用debug有加载不到so这个错误。
[DEBUG] - 当前库加载器: OnnxLinuxX8664LibraryLoader
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/ocrJava/onnx/libRapidOcr.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[DEBUG] - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/ocrJava/onnx/libRapidOcr.so)
[ERROR] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/ocrJava/onnx/libRapidOcr.so)] with root cause
java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/ocrJava/onnx/libRapidOcr.so
-----------
[DEBUG] - 当前模型加载器: OnnxModelsLoader
[DEBUG] - 将文件models/ch_PP-OCRv3_det_infer.onnx复制到/onnx，加载此文件：false，JVM退出时删除此文件：false
[DEBUG] - 将文件models/ch_ppocr_mobile_v2.0_cls_infer.onnx复制到/onnx，加载此文件：false，JVM退出时删除此文件：false
[DEBUG] - 将文件models/ch_PP-OCRv3_rec_infer.onnx复制到/onnx，加载此文件：false，JVM退出时删除此文件：false
[DEBUG] - 将文件models/ppocr_keys_v1.txt复制到/onnx，加载此文件：false，JVM退出时删除此文件：false
[DEBUG] - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.benjaminwan.ocrlibrary.OcrEngine.initLogger(ZZZ)V
[ERROR] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.benjaminwan.ocrlibrary.OcrEngine.initLogger(ZZZ)V] with root cause

**Comment by MyMonsterCat** [comment]
> 目前在windows上打包的话，只会带上windows的dll，没有linux的so。 建议手动在 pom.xml 加一个依赖 `rapidocr-onnx-linux-x86_64`

关于Linux上运行请参考：[如何打包 jar 在Linux系统上运行](https://github.com/MyMonsterCat/RapidOcr-Java/blob/main/docs/COMPILE_JAR.md)

**Comment by MyMonsterCat** [comment]
> > 如果还是不行的话。建议写一个demo代码，还有jar包，可以复现这个问题的
> 
> ## 今天在阿里云用docker，跑也是一样的错误，不用debug有加载不到so这个错误。
> [DEBUG] - 当前库加载器: OnnxLinuxX8664LibraryLoader
> OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/ocrJava/onnx/libRapidOcr.so which might have disabled stack guard. The VM will try to fix the stack guard now.
> It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
> [DEBUG] - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/ocrJava/onnx/libRapidOcr.so)
> [ERROR] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/ocrJava/onnx/libRapidOcr.so)] with root cause
> java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/ocrJava/onnx/libRapidOcr.so
> [DEBUG] - 当前模型加载器: OnnxModelsLoader [DEBUG] - 将文件models/ch_PP-OCRv3_det_infer.onnx复制到/onnx，加载此文件：false，JVM退出时删除此文件：false [DEBUG] - 将文件models/ch_ppocr_mobile_v2.0_cls_infer.onnx复制到/onnx，加载此文件：false，JVM退出时删除此文件：false [DEBUG] - 将文件models/ch_PP-OCRv3_rec_infer.onnx复制到/onnx，加载此文件：false，JVM退出时删除此文件：false [DEBUG] - 将文件models/ppocr_keys_v1.txt复制到/onnx，加载此文件：false，JVM退出时删除此文件：false [DEBUG] - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.benjaminwan.ocrlibrary.OcrEngine.initLogger(ZZZ)V [ERROR] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.benjaminwan.ocrlibrary.OcrEngine.initLogger(ZZZ)V] with root cause

请问这个问题解决了吗？能否提供一个demo。

**Comment by MyMonsterCat** [comment]
> 没呢，目前发现的一个问题 rapidOcr 不能在 alpine 上运行，alpine 是一个微型的 linux，里面缺了一些so文件，正好就有 rapidOcr 需要的

可以看下这个[如何在CentOS7或其他低版本Linux系统上运行](https://github.com/MyMonsterCat/RapidOcr-Java/blob/main/docs/CentOS7.md)。不过微型的 linux估计很难编译，内存不大，可以试试使用SCL安装和配置

**Comment by jilcdeerchao-lgtm** [comment]
已经引入了rapidocr-onnx-linux-x86_64包，运行在docker里面，还是抛出异常：
jakarta.servlet.ServletException: Handler dispatch failed: java.lang.UnsatisfiedLinkError: /tmp/ocrJava/onnx/libRapidOcr.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/ocrJava/onnx/libRapidOcr.so)

	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1104)

	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)

	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)

	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)

	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)

	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)

	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)

	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)

	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
