### ISSUE TITLE
还是要有onnx的好，官方模型转换好像只提供了onnx

### ISSUE THREAD

**Issue by nn200433** [MyMonsterCat/RapidOcr-Java#2]
![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/15652213/03a06108-7f91-433b-bcf2-c7e54505b5b9)

**Comment by MyMonsterCat** [comment]
感谢使用和反馈，近期会集成ONNX，同时欢迎您提交PR实现该功能

**Comment by nn200433** [comment]
> 感谢使用和反馈，近期会集成ONNX，同时欢迎您提交PR实现该功能

菜鸡刚偷的大佬代码 :joy: [tika-server](https://github.com/nn200433/tika-server)
![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/15652213/168a5fed-c1ed-4274-8239-f781502cd3df)

**Comment by MyMonsterCat** [comment]
1. 大佬谦虚啦，我看了您的项目集成ncnn的部分代码，受益匪浅，小小参考（cv）了一下。
2. 已集成ONNX，版本号为0.0.3
