### ISSUE TITLE
运行测试代码 发生错误

### ISSUE THREAD

**Issue by hbbdjw** [MyMonsterCat/RapidOcr-Java#20]
"C:\Program Files\Java\jdk1.8.0_281\bin\java.exe" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2023.1\lib\idea_rt.jar=60651:D:\Program Files\JetBrains\IntelliJ IDEA 2023.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_281\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_281\jre\lib\rt.jar;E:\test\rapidocr-demo-main\java-ee\target\classes;D:\maven\m2\repository\io\github\mymonstercat\rapidocr\0.0.7\rapidocr-0.0.7.jar;D:\maven\m2\repository\io\github\mymonstercat\rapidocr-common\0.0.7\rapidocr-common-0.0.7.jar;D:\maven\m2\repository\io\github\mymonstercat\rapidocr-onnx-platform\0.0.7\rapidocr-onnx-platform-0.0.7.jar;D:\maven\m2\repository\io\github\mymonstercat\rapidocr-onnx-windows-x86_64\1.2.2\rapidocr-onnx-windows-x86_64-1.2.2.jar;D:\maven\m2\repository\io\github\mymonstercat\rapidocr-onnx-models\1.2.2\rapidocr-onnx-models-1.2.2.jar;D:\maven\m2\repository\junit\junit\4.13.1\junit-4.13.1.jar;D:\maven\m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;D:\maven\m2\repository\cn\hutool\hutool-core\5.8.20\hutool-core-5.8.20.jar;D:\maven\m2\repository\org\projectlombok\lombok\1.18.28\lombok-1.18.28.jar;D:\maven\m2\repository\org\slf4j\slf4j-simple\2.0.7\slf4j-simple-2.0.7.jar;D:\maven\m2\repository\org\slf4j\slf4j-api\2.0.7\slf4j-api-2.0.7.jar" io.github.mymonstercat.Main
Model dbnet file not found: C:\Users\13472\AppData\Local\Temp\ocrJava/onnx/ch_PP-OCRv4_det_infer.onnx.param
[main] INFO com.benjaminwan.ocrlibrary.OcrEngine - 推理引擎初始化完成，当前使用的推理引擎为：onnx-v1.1.1
[main] INFO com.benjaminwan.ocrlibrary.OcrEngine - 初始化时模型配置为：Model.ONNX_PPOCR_V4(modelsDir=/models, modelType=onnx, detName=ch_PP-OCRv4_det_infer.onnx, clsName=ch_ppocr_mobile_v2.0_cls_infer.onnx, recName=ch_PP-OCRv4_rec_infer.onnx, keysName=ppocr_keys_v1.txt)， 硬件配置为：HardwareConfig(numThread=8, gpuIndex=-1)
[main] INFO io.github.mymonstercat.ocr.InferenceEngine - 图片路径：C:\Users\13472\AppData\Local\Temp\ocrJava/img.png， 参数配置：ParamConfig(padding=50, maxSideLen=0, boxScoreThresh=0.5, boxThresh=0.3, unClipRatio=1.6, doAngle=true, mostAngle=true)
find_blob_index_by_name input failed
Try
find_blob_index_by_name output failed
Try
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb0e7c694b, pid=26796, tid=0x0000000000007900
#
# JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build 1.8.0_281-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [RapidOcr.dll+0x7b694b]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\test\rapidocr-demo-main\hs_err_pid26796.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
numThread=8
modelsDir=C:\Users\13472\AppData\Local\Temp\ocrJava/onnx
det=ch_PP-OCRv4_det_infer.onnx
cls=ch_ppocr_mobile_v2.0_cls_infer.onnx
rec=ch_PP-OCRv4_rec_infer.onnx
keys=ppocr_keys_v1.txt
imgDir=C:\Users\13472\AppData\Local\Temp\ocrJava/, imgName=img.png

进程已结束，退出代码为 1

**Comment by MyMonsterCat** [comment]
提供一下使用代码或复现demo？

**Comment by hbbdjw** [comment]
> 我在全新win11设备上使用没有修复这个问题，能否提供一下使用代码或修复演示文稿？

使用的 https://github.com/MyMonsterCat/rapidocr-demo.git 这个代码，未作任何修改。我怀疑是jdk版本导致的，我用的是jdk1.8.0_281 ，尝试过降低版本（1.8.0_66），但不起作用.
