### ISSUE TITLE
WIN10调试Demo报错

### ISSUE THREAD

**Issue by chinasxlym** [MyMonsterCat/RapidOcr-Java#23]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ff89797cf19, pid=41616, tid=40380
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x2cf19]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x0000000002de9000):  JavaThread "main" [_thread_in_native, id=40380, stack(0x0000000002c50000,0x0000000002d50000)]

siginfo: ExceptionCode=0xe06d7363, ExceptionInformation=0x0000000019930520 0x0000000002d4f0f0 0x00007ff802bb2c18 0x00007ff801c90000 

Registers:
RAX=0x0000000000000000, RBX=0x00007ff802bb2c18, RCX=0x0000000000000000, RDX=0x0000000000000000
RSP=0x0000000002d4ef70, RBP=0x0000000000a72e60, RSI=0x0000000002d4f0f0, RDI=0x0000000019930520
R8 =0x0000000000a00000, R9 =0x0000000002d4e990, R10=0x0000000000000000, R11=0x0000000000000000
R12=0x000000003d292840, R13=0x0000000000000000, R14=0x0000000000a72e70, R15=0x0000000000000030
RIP=0x00007ff89797cf19, EFLAGS=0x0000000000000202

Top of Stack: (sp=0x0000000002d4ef70)
0x0000000002d4ef70:   0000000000000000 00007ff802bb2c18
0x0000000002d4ef80:   0000000002d4f0f0 000000003f800000
0x0000000002d4ef90:   00000001e06d7363 0000000000000000
0x0000000002d4efa0:   00007ff89797cf19 0000000000000004
0x0000000002d4efb0:   0000000019930520 0000000002d4f0f0
0x0000000002d4efc0:   00007ff802bb2c18 00007ff801c90000
0x0000000002d4efd0:   0000000000000000 000000003d292840
0x0000000002d4efe0:   0000000002d4f0f0 0000000000a72e60
0x0000000002d4eff0:   0000000002d4f070 00007ff89a144a5f
0x0000000002d4f000:   0000000019930520 00007ff800000000
0x0000000002d4f010:   000000003d2bf710 00007ff89a1347b1
0x0000000002d4f020:   00007ff802d27000 00007ff801c90000
0x0000000002d4f030:   00006ec314fd3cf3 00007ff801c97934
0x0000000002d4f040:   00007ff802bb2c18 00007ff8027e7e50
0x0000000002d4f050:   000000003d2bf710 00007ff802818d28
0x0000000002d4f060:   0000000000000030 0000000000000000 

Instructions: (pc=0x00007ff89797cf19)
0x00007ff89797cef9:   8b d1 44 0f 47 c0 44 89 44 24 38 49 c1 e0 03 e8
0x00007ff89797cf09:   3a 99 08 00 48 8d 4c 24 20 48 ff 15 4f 81 1b 00
0x00007ff89797cf19:   0f 1f 44 00 00 48 8b 8c 24 c0 00 00 00 48 33 cc
0x00007ff89797cf29:   e8 32 89 06 00 48 81 c4 d8 00 00 00 c3 cc 83 64 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00007ff802bb2c18 is an unknown value
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x0000000002d4ef70 is pointing into the stack for thread: 0x0000000002de9000
RBP=0x0000000000a72e60 is an unknown value
RSI=0x0000000002d4f0f0 is pointing into the stack for thread: 0x0000000002de9000
RDI=0x0000000019930520 is an unknown value
R8 =0x0000000000a00000 is an unknown value
R9 =0x0000000002d4e990 is pointing into the stack for thread: 0x0000000002de9000
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000000 is an unknown value
R12=0x000000003d292840 is an unknown value
R13=0x0000000000000000 is an unknown value
R14=0x0000000000a72e70 is an unknown value
R15=0x0000000000000030 is an unknown value

Stack: [0x0000000002c50000,0x0000000002d50000],  sp=0x0000000002d4ef70,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [KERNELBASE.dll+0x2cf19]
C  [RapidOcr.dll+0xb57e50]
C  [RapidOcr.dll+0x751e]
C  [RapidOcr.dll+0xfbde]
C  [RapidOcr.dll+0x16087]
C  [RapidOcr.dll+0x17cd4]
C  0x0000000002ef7f54

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.benjaminwan.ocrlibrary.OcrEngine.initModels(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z+0
j  com.benjaminwan.ocrlibrary.OcrEngine.initEngine(Lio/github/mymonstercat/Model;Lio/github/mymonstercat/ocr/config/HardwareConfig;)V+71
j  io.github.mymonstercat.ocr.InferenceEngine.runOcr(Ljava/lang/String;Lio/github/mymonstercat/ocr/config/ParamConfig;)Lcom/benjaminwan/ocrlibrary/OcrResult;+16
j  io.github.mymonstercat.ocr.InferenceEngine.runOcr(Ljava/lang/String;)Lcom/benjaminwan/ocrlibrary/OcrResult;+5
j  org.dream.ocr.controller.Test.main([Ljava/lang/String;)V+10
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x000000003a97f800 JavaThread "Service Thread" daemon [_thread_blocked, id=43728, stack(0x000000003b350000,0x000000003b450000)]
  0x000000003a8fd800 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=43128, stack(0x000000003b250000,0x000000003b350000)]
  0x000000003a8f9800 JavaThread "C2 CompilerThread2" daemon [_thread_in_native, id=4312, stack(0x000000003b150000,0x000000003b250000)]
  0x000000003a8ed000 JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=3096, stack(0x000000003b050000,0x000000003b150000)]
  0x000000003a894800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=38368, stack(0x000000003af50000,0x000000003b050000)]
  0x000000003a892000 JavaThread "Attach Listener" daemon [_thread_blocked, id=42936, stack(0x000000003ae50000,0x000000003af50000)]
  0x000000003a8eb000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=43512, stack(0x000000003ad50000,0x000000003ae50000)]
  0x000000003a870800 JavaThread "Finalizer" daemon [_thread_blocked, id=39908, stack(0x000000003ac50000,0x000000003ad50000)]
  0x000000003897f800 JavaThread "Reference Handler" daemon [_thread_blocked, id=42884, stack(0x000000003a750000,0x000000003a850000)]
=>0x0000000002de9000 JavaThread "main" [_thread_in_native, id=40380, stack(0x0000000002c50000,0x0000000002d50000)]

Other Threads:
  0x0000000038977800 VMThread [stack: 0x000000003a650000,0x000000003a750000] [id=30648]
  0x000000003aa59800 WatcherThread [stack: 0x000000003b450000,0x000000003b550000] [id=37332]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 305152K, used 20957K [0x000000066bb00000, 0x0000000680f80000, 0x00000007c0000000)
  eden space 261632K, 8% used [0x000000066bb00000,0x000000066cf774d8,0x000000067ba80000)
  from space 43520K, 0% used [0x000000067e500000,0x000000067e500000,0x0000000680f80000)
  to   space 43520K, 0% used [0x000000067ba80000,0x000000067ba80000,0x000000067e500000)
 ParOldGen       total 697856K, used 0K [0x00000003c3000000, 0x00000003ed980000, 0x000000066bb00000)
  object space 697856K, 0% used [0x00000003c3000000,0x00000003c3000000,0x00000003ed980000)
 Metaspace       used 5152K, capacity 5304K, committed 5504K, reserved 1056768K
  class space    used 574K, capacity 596K, committed 640K, reserved 1048576K

Card table byte_map: [0x00000000122a0000,0x0000000014290000] byte_map_base: 0x0000000010488000

Marking Bits: (ParMarkBitMap*) 0x000000005f552f70
 Begin Bits: [0x0000000015fe0000, 0x0000000025f20000)
 End Bits:   [0x0000000025f20000, 0x0000000035e60000)

Polling page: 0x0000000000f90000

CodeCache: size=245760Kb used=2219Kb max_used=2219Kb free=243540Kb
 bounds [0x0000000002ee0000, 0x0000000003150000, 0x0000000011ee0000]
 total_blobs=706 nmethods=402 adapters=215
 compilation: enabled

Compilation events (10 events):
Event: 0.673 Thread 0x000000003a894800  399   !   4       java.util.zip.Inflater::inflate (113 bytes)
Event: 0.676 Thread 0x000000003a894800 nmethod 399 0x00000000030fc110 code [0x00000000030fc260, 0x00000000030fc708]
Event: 0.742 Thread 0x000000003a8ed000  400   !   4       java.util.zip.InflaterInputStream::read (138 bytes)
Event: 0.761 Thread 0x000000003a8ed000 nmethod 400 0x000000000310af10 code [0x000000000310b0e0, 0x000000000310cc88]
Event: 0.771 Thread 0x000000003a8f9800  401       4       java.io.FilterInputStream::read (9 bytes)
Event: 0.772 Thread 0x000000003a894800  402       4       java.io.FilterInputStream::read (11 bytes)
Event: 0.772 Thread 0x000000003a8ed000  403  s    4       java.nio.channels.Channels$1::write (107 bytes)
Event: 0.772 Thread 0x000000003a8f9800 nmethod 401 0x00000000030fa650 code [0x00000000030fa7a0, 0x00000000030fa8a8]
Event: 0.772 Thread 0x000000003a8f9800  404   !   4       java.nio.channels.Channels::writeFully (60 bytes)
Event: 0.772 Thread 0x000000003a894800 nmethod 402 0x00000000030fbe10 code [0x00000000030fbf60, 0x00000000030fc028]

GC Heap History (0 events):
No events

Deoptimization events (4 events):
Event: 0.180 Thread 0x0000000002de9000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000002fe3704 method=java.lang.String.hashCode()I @ 14
Event: 0.374 Thread 0x0000000002de9000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000003014d00 method=java.lang.CharacterData.of(I)Ljava/lang/CharacterData; @ 4
Event: 0.632 Thread 0x0000000002de9000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000003052cdc method=sun.nio.cs.UTF_8$Encoder.encode([CII[B)I @ 33
Event: 0.634 Thread 0x0000000002de9000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000000030e5094 method=java.io.WinNTFileSystem.isLetter(C)Z @ 3

Internal exceptions (10 events):
Event: 0.331 Thread 0x0000000002de9000 Exception <a 'java/security/PrivilegedActionException'> (0x000000066c6d5a40) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.331 Thread 0x0000000002de9000 Exception <a 'java/security/PrivilegedActionException'> (0x000000066c6d5c50) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.331 Thread 0x0000000002de9000 Exception <a 'java/security/PrivilegedActionException'> (0x000000066c6d6a80) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.331 Thread 0x0000000002de9000 Exception <a 'java/security/PrivilegedActionException'> (0x000000066c6d6c90) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.376 Thread 0x0000000002de9000 Exception <a 'java/io/FileNotFoundException'> (0x000000066c832820) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.449 Thread 0x0000000002de9000 Exception <a 'sun/nio/fs/WindowsException'> (0x000000066ca14d48) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.634 Thread 0x0000000002de9000 Exception <a 'sun/nio/fs/WindowsException'> (0x000000066ca37428) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.662 Thread 0x0000000002de9000 Exception <a 'sun/nio/fs/WindowsException'> (0x000000066ca416b8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.668 Thread 0x0000000002de9000 Exception <a 'sun/nio/fs/WindowsException'> (0x000000066ca4b500) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.777 Thread 0x0000000002de9000 Exception <a 'sun/nio/fs/WindowsException'> (0x000000066ca5b4f0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u91\6644\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 0.632 Thread 0x0000000002de9000 Uncommon trap: trap_request=0xffffff65 fr.pc=0x0000000003052cdc
Event: 0.632 Thread 0x0000000002de9000 DEOPT PACKING pc=0x0000000003052cdc sp=0x0000000002d4ec70
Event: 0.632 Thread 0x0000000002de9000 DEOPT UNPACKING pc=0x0000000002f2582a sp=0x0000000002d4ec08 mode 2
Event: 0.633 loading class io/github/mymonstercat/OnnxModelsLoader
Event: 0.633 loading class io/github/mymonstercat/OnnxModelsLoader done
Event: 0.634 loading class io/github/mymonstercat/loader/ModelsLoader
Event: 0.634 loading class io/github/mymonstercat/loader/ModelsLoader done
Event: 0.634 Thread 0x0000000002de9000 Uncommon trap: trap_request=0xffffff65 fr.pc=0x00000000030e5094
Event: 0.634 Thread 0x0000000002de9000 DEOPT PACKING pc=0x00000000030e5094 sp=0x0000000002d4f1b0
Event: 0.634 Thread 0x0000000002de9000 DEOPT UNPACKING pc=0x0000000002f2582a sp=0x0000000002d4f048 mode 2

Dynamic libraries:
0x00007ff759fd0000 - 0x00007ff75a007000 	C:\Program Files\Java\jdk1.8.0_91\bin\javaw.exe
0x00007ff89a110000 - 0x00007ff89a308000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ff899d50000 - 0x00007ff899e0d000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ff897950000 - 0x00007ff897c46000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ff898730000 - 0x00007ff8987df000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ff899350000 - 0x00007ff8993ee000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ff899530000 - 0x00007ff8995cc000 	C:\WINDOWS\System32\sechost.dll
0x00007ff898ff0000 - 0x00007ff899116000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ff8995d0000 - 0x00007ff89976e000 	C:\WINDOWS\System32\USER32.dll
0x00007ff897ea0000 - 0x00007ff897ec2000 	C:\WINDOWS\System32\win32u.dll
0x00007ff89a0a0000 - 0x00007ff89a0cc000 	C:\WINDOWS\System32\GDI32.dll
0x00007ff897d80000 - 0x00007ff897e9a000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ff897ed0000 - 0x00007ff897f6d000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ff898020000 - 0x00007ff898120000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ff87eb50000 - 0x00007ff87edea000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\COMCTL32.dll
0x00007ff8998b0000 - 0x00007ff8998e0000 	C:\WINDOWS\System32\IMM32.DLL
0x0000000066950000 - 0x0000000066a22000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\msvcr100.dll
0x000000005ed40000 - 0x000000005f5d3000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\server\jvm.dll
0x00007ff8998a0000 - 0x00007ff8998a8000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ff88b7e0000 - 0x00007ff88b807000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ff895f90000 - 0x00007ff895f9a000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ff882090000 - 0x00007ff882099000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ff899200000 - 0x00007ff89926b000 	C:\WINDOWS\System32\WS2_32.dll
0x0000000067970000 - 0x000000006797f000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\verify.dll
0x0000000066920000 - 0x0000000066949000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\java.dll
0x0000000066900000 - 0x0000000066916000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\zip.dll
0x00007ff898840000 - 0x00007ff898f85000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ff8955e0000 - 0x00007ff895d7b000 	C:\WINDOWS\SYSTEM32\windows.storage.dll
0x00007ff898170000 - 0x00007ff8984c4000 	C:\WINDOWS\System32\combase.dll
0x00007ff897230000 - 0x00007ff89725d000 	C:\WINDOWS\SYSTEM32\Wldp.dll
0x00007ff899480000 - 0x00007ff89952d000 	C:\WINDOWS\System32\SHCORE.dll
0x00007ff899120000 - 0x00007ff899175000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ff897720000 - 0x00007ff897745000 	C:\WINDOWS\SYSTEM32\profapi.dll
0x00000000668e0000 - 0x00000000668fa000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\net.dll
0x00007ff873f60000 - 0x00007ff873f80000 	C:\WINDOWS\system32\PrxerDrv.dll
0x00007ff896f90000 - 0x00007ff896ffa000 	C:\WINDOWS\system32\mswsock.dll
0x00000000668c0000 - 0x00000000668d1000 	C:\Program Files\Java\jdk1.8.0_91\jre\bin\nio.dll
0x00007ff801c90000 - 0x00007ff802d99000 	C:\Users\李永茂\AppData\Local\Temp\ocrJava\onnx\RapidOcr.dll
0x00007ff8962e0000 - 0x00007ff8962f2000 	C:\WINDOWS\SYSTEM32\kernel.appcore.dll
0x00007ff892e20000 - 0x00007ff893004000 	C:\WINDOWS\SYSTEM32\dbghelp.dll
0x00007ff897cc0000 - 0x00007ff897d42000 	C:\WINDOWS\System32\bcryptPrimitives.dll

VM Arguments:
jvm_args: -Dfile.encoding=UTF-8 
java_command: org.dream.ocr.controller.Test
java_class_path (initial): C:\workspace\dream-ocr\target\classes;D:\repo\org\springframework\spring-aop\5.3.14\spring-aop-5.3.14.jar;D:\repo\org\springframework\spring-beans\5.3.14\spring-beans-5.3.14.jar;D:\repo\org\springframework\spring-context\5.3.14\spring-context-5.3.14.jar;D:\repo\org\springframework\spring-context-support\5.3.14\spring-context-support-5.3.14.jar;D:\repo\org\springframework\spring-core\5.3.14\spring-core-5.3.14.jar;D:\repo\org\springframework\spring-jcl\5.3.14\spring-jcl-5.3.14.jar;D:\repo\org\springframework\spring-tx\5.3.14\spring-tx-5.3.14.jar;D:\repo\org\springframework\spring-web\5.3.14\spring-web-5.3.14.jar;D:\repo\org\springframework\spring-websocket\5.3.14\spring-websocket-5.3.14.jar;D:\repo\org\springframework\spring-webmvc\5.3.14\spring-webmvc-5.3.14.jar;D:\repo\org\springframework\spring-expression\5.3.14\spring-expression-5.3.14.jar;D:\repo\org\springframework\spring-jdbc\5.3.14\spring-jdbc-5.3.14.jar;D:\repo\javax\servlet\javax.servlet-api\4.0.1\javax.servlet-api-4.0.1.jar;D:\repo\org\slf4j\slf4j-api\1.7.9\slf4j-api-1.7.9.jar;D:\repo\ch\qos\logback\logback-core\1.2.10\logback-core-1.2.10.jar;D:\repo\ch\qos\logback\logback-classic\1.2.10\logback-classic-1.2.10.jar;D:\repo\ch\qos\logback\logback-access\1.2.10\logback-access-1.2.10.jar;D:\repo\io\github\mymonstercat\rapidocr\0.0.7\rapidocr-0.0.7.jar;D:\repo\io\github\mymonstercat\rapidocr-common\0.0.7\rapidocr-common-0.0.7.jar;D:\repo\io\github\mymonstercat\rapidocr-onnx-platform\0.0.7\rapidocr-onnx-platform-0.0.7.jar;D:\repo\io\github\mymonstercat\rapidocr-onnx-windows-x86_64\1.2.2\rapidocr-onnx-windows-x86_64-1.2.2.jar;D:\repo\io\github\mymonstercat\rapidocr-onnx-models\1.2.2\rapidocr-onnx-models-1.2.2.jar;C:\workspace\dream-core\target\classes;D:\repo\org\springframework\spring-messaging\5.3.14\spring-messaging-5.3.14.jar;D:\repo\org\freemarker\freemarker\2.3.30\freemarker-2.3.30.jar;D:\repo\org\springframework\mobile\spring-mobile-device\1.1.3.RELEASE\spring-mobile-device-1.1.
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_91
PATH=C:\SuperMap\SuperMap iDesktop 11i\Bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\oracle\product\11.2.0\client_1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Bitvise SSH Client;C:\Oracle\Ora81\bin;C:\Program Files\Java\jdk1.8.0_91\bin;C:\maven-3.5.2\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Autodesk\Revit 2020;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;c:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Java\jdk1.8.0_91\bin;C:\Users\李永茂\AppData\Local\Microsoft\WindowsApps;C:\Users\李永茂\AppData\Local\Yarn\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\JetBrains\WebStorm 2019.3\bin;;C:\Users\李永茂\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\李永茂\AppData\Roaming\npm;C:\Users\李永茂\.dotnet\tools;
USERNAME=李永茂
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 19041 (10.0.19041.3636)

CPU:total 8 (4 cores per cpu, 2 threads per core) family 6 model 158 stepping 9, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 66911756k(41042904k free), swap 76873228k(40997288k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.91-b14) for windows-amd64 JRE (1.8.0_91-b14), built on Apr  1 2016 00:58:32 by "java_re" with MS VC++ 10.0 (VS2010)

time: Wed Dec 27 06:56:34 2023
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by XimfengYao** [comment]
[hs_err_pid41516.log](https://github.com/MyMonsterCat/RapidOcr-Java/files/14534439/hs_err_pid41516.log)
@MyMonsterCat 大佬win10调用出现错误。以上是日志错误
