### ISSUE TITLE
部署到linux服务器上报错，能指教下是啥情况吗

### ISSUE THREAD

**Issue by luhuifeng** [MyMonsterCat/RapidOcr-Java#24]
![408cdf96a4fd133b1b8d6335f3524e9](https://github.com/MyMonsterCat/RapidOcr-Java/assets/37391857/86c8d988-162a-4044-a145-3e4c3d9ef6dd)
部署到linux上报图上的错误

**Comment by MyMonsterCat** [comment]
参考一下文档，你有添加linux版本的依赖吗
