### ISSUE TITLE
坐标有负值

### ISSUE THREAD

**Issue by scvzerng** [MyMonsterCat/RapidOcr-Java#27]
为什么识别结果坐标有负值
![1705483431158](https://github.com/MyMonsterCat/RapidOcr-Java/assets/14892120/e6c52971-0c68-436c-9b4a-4274ad0c8be8)

**Comment by MyMonsterCat** [comment]
能否提供一下图片？

**Comment by scvzerng** [comment]
> 能否提供一下图片？

![test](https://github.com/MyMonsterCat/RapidOcr-Java/assets/14892120/4282b247-9ff3-45d2-9c25-e7ef3b0fa961)

就这个吧 虽然不影响使用但是总觉得很奇怪 我是用的ffi调用的c库发现有负数坐标又特意用的java版的发现一样的问题 应该是c++那边的算法问题
