### ISSUE TITLE
急！springboot打成war包在tomcat中运行报错ocrJava\\onnx\\RapidOcr.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform

### ISSUE THREAD

**Issue by wang-dad** [MyMonsterCat/RapidOcr-Java#28]
请教一下   springboot打成war包在tomcat中运行报错ocrJava\\onnx\\RapidOcr.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform。
jar包是正常，但是项目要求只能用war包。

**Comment by wang-dad** [comment]
`    implementation('io.github.mymonstercat:rapidocr:0.0.7') {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
    implementation 'io.github.mymonstercat:rapidocr-onnx-platform:0.0.7'`  我的gralde依赖就是用的这个，打成war包报上面那个错，现在解决了，从你仓库下载了个64位的替换了一下，不过有点麻烦

**Comment by MyMonsterCat** [comment]
好滴，这边我抽空优化一下
