### ISSUE TITLE
Windows server 上用不了，Windows的服务器版本系统，不是平时用的Windows系列

### ISSUE THREAD

**Issue by hellowaiwai** [MyMonsterCat/RapidOcr-Java#29]

**Comment by bigsheng15** [comment]
老哥你怎么解决的

**Comment by bigsheng15** [comment]
老哥你怎么解决的 @hellowaiwai

**Comment by roostinghawk** [comment]
Linxu 上正常，我们在 windows server 上运行后，错误信息如下：
Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: 'void com.benjaminwan.ocrlibrary.OcrEngine.setGpuIndex(int)'

**Comment by bigsheng15** [comment]
你好，我已收到邮件，我将稍后查看你的邮件，谢谢！
