### ISSUE TITLE
图片 byte[]支持

### ISSUE THREAD

**Issue by scvzerng** [MyMonsterCat/RapidOcr-Java#3]
```java
 public native OcrResult detect(
            String input, int padding, int maxSideLen,
            float boxScoreThresh, float boxThresh,
            float unClipRatio, boolean doAngle, boolean mostAngle
    );
```
input参数能否支持传递byte[] 有些场景比如屏幕截屏之后再写入本地再获取图片路径的话比较冗余

**Comment by MyMonsterCat** [comment]
感谢反馈，由于这是native方法，受限于相应的C/C++代码，地址[RapidOcrOnnx/](https://github.com/RapidAI/RapidOcrOnnx/tree/main)。暂时没有动这里的打算，有兴趣你可以研究下，欢迎提交PR。
或者可以使用onnxruntime的Java api，那里传参可以是 图片转成的多维数组。（目前这个项目还在开发中，短时间内无法公开)。

**Comment by scvzerng** [comment]
为了传bytes入门了c++这是个菜鸡c++的实现大佬帮忙看下是否可行以下是两个fork的仓库
[RapidOcr-Java](https://github.com/scvzerng/RapidOcr-Java.git)；
[RapidOcrOnnx](https://github.com/scvzerng/RapidOcrOnnx.git)；
设备有限目前只在windows64位平台进行了测试

**Comment by MyMonsterCat** [comment]
牛p，我这个月情况特殊没有设备(内网出不去)，下个月我回去了再膜拜一下代码。如果可以的话您可以提交个PR
