### ISSUE TITLE
使用服务器版模型库

### ISSUE THREAD

**Issue by shadowyy** [MyMonsterCat/RapidOcr-Java#30]
我看模型使用的是ch_PP-OCRv4_det_infer.onnx，怎么使用ch_PP-OCRv4_det_server_infer.onnx，服务器的模型，包括ch_PP-OCRv4_rec_infer.onnx也是

**Comment by MyMonsterCat** [comment]
这个需要试一下能不能用。
1.把代码拉下来
2.替换一下模型看能不能跑。
我没有试过，可能需要你自己试一下。
最近比较忙，下个月尽量我了解一下这方面。

**Comment by shadowyy** [comment]
试了下可以的，识别率也提升了不少，谢谢~

**Comment by MyMonsterCat** [comment]
np，老哥如果改好了不嫌麻烦的话可以提个PR😁

**Comment by fuxianwen** [comment]
咋玩的

**Comment by xulihang** [comment]
还有其它语言的模型也需要能够调用，能指定路径应该要方便一点
