### ISSUE TITLE
报错 java.lang.NullPointerException:

### ISSUE THREAD

**Issue by anxiglog** [MyMonsterCat/RapidOcr-Java#34]
pom  只引入以下
![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/39998273/81092fbf-88b5-4df3-87ff-38761140153f)

本地windows 能运行  但是打包后  linux 上报错
![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/39998273/5687a442-2927-40a6-896d-49fe16d8650c)

**Comment by MyMonsterCat** [comment]
没引入linux包，文档中有写哈
