### ISSUE TITLE
多线程并发支持

### ISSUE THREAD

**Issue by llm163520** [MyMonsterCat/RapidOcr-Java#36]
![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/22343834/9a3e1959-2ed1-4526-bcc0-71e852bae68c)
1、如上图，这块是否可以调整到初始化的时候；不用每次运行都去重新加载
2、多线程并发识别支持

**Comment by MyMonsterCat** [comment]
受限于底层c++代码，暂时不支持

**Comment by llm163520** [comment]
ok

**Comment by FlyInWind1** [comment]
![图片](https://github.com/MyMonsterCat/RapidOcr-Java/assets/29172747/5866e661-ebe0-45ee-a67c-ab0a1ae25834)
initEngine 方法里面，有判断是否加载过。并发识别是没有问题的
