### ISSUE TITLE
windows没办法识别验证码

### ISSUE THREAD

**Issue by chenhailong118** [MyMonsterCat/RapidOcr-Java#37]
![output](https://github.com/MyMonsterCat/RapidOcr-Java/assets/9260730/c012d029-9642-46f8-a3a6-983305cd79b9)
10:09:17.663 [main] INFO  i.g.m.o.InferenceEngine - [runOcr,57] - 图片路径：images/output.jpg， 参数配置：ParamConfig(padding=50, maxSideLen=0, boxScoreThresh=0.5, boxThresh=0.3, unClipRatio=1.6, doAngle=false, mostAngle=false)
10:09:17.687 [main] INFO  i.g.m.o.InferenceEngine - [runOcr,59] - 识别结果为：，耗时17.899000003933907ms
##################，

**Comment by MyMonsterCat** [comment]
使用的模型不适应复杂的验证码，可以考虑一下ddddocr
