### ISSUE TITLE
如何在springboot项目中同时使用多种识别模型

### ISSUE THREAD

**Issue by liuz198711** [MyMonsterCat/RapidOcr-Java#38]
楼主您好，在springboot中引入这个库做OCR识别时，我们对几类不同的验证码分别训练了针对性的文本识别模型，所以需要根据所识别的验证码是哪一类使用不同的模型进行识别。现在遇到问题是，项目启动后第一次调用使用的模型就不能再变了，无法满足以上场景。这个能有解决办法吗？本人水平不高，研究了代码还是没找到解决办法，如有还希望回复，非常感谢

**Comment by MyMonsterCat** [comment]
不好意思还不支持，如果要改需要从c代码入手。
