### ISSUE TITLE
通过java 版本onnx-runtime调用并使用模型，这个方式开发在进行中嘛？可以申请参与嘛

### ISSUE THREAD

**Issue by Gmgge** [MyMonsterCat/RapidOcr-Java#39]
个人在图像上面稍有涉猎，也有这个方向尝试的想法，能否参与一些工作呢？

**Comment by MyMonsterCat** [comment]
你好，只做了一些初期工作，例如裁剪后的识别已经完成，但由于工作原因(出差)，暂时搁置了。如果有兴趣一起研究Java版本的，留个联系方式，向您请教学习一下

**Comment by Gmgge** [comment]
我看到onnxruntime 的java api 介绍，看来实现还是走jni这步，This directory contains the Java language binding for the ONNX runtime. Java Native Interface (JNI) is used to allow for seamless calls to ONNX runtime from Java. 不同平台仍然会存在适配问题。

可以联系我的邮箱ypoy66378@163.com
