### ISSUE TITLE
非常感谢作者提供的库，解决了很大的 OCR 集成问题。 基于教程已在 arm64 银河麒麟 v10 上成功打包动态库，可否提交 pull-request？

### ISSUE THREAD

**Issue by sandywalker** [MyMonsterCat/RapidOcr-Java#42]
感谢作者，由于我们开发的项目基于信创环境，基于 paddleocr 无论是 pip 安装还是 install 都非常困难。后来找到 RapidOcr 和 RapidOcr-Java 库，开发集成都非常方便。我们公司提供了 arm64 的银河麒麟环境，我下载了 [RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx) 库的代码，并成功编译出 LibRapidOcrOnnx.so 文件。如果您不介意，我做完一定的测试，提交一下 pull-request

**Comment by FlyInWind1** [comment]
老哥有没有遇见过这样的情况，操作系统自带的gcc版本太低了

**Comment by sandywalker** [comment]
目标机器的 gcc 版本还行，我们的情况是只有 gcc 没有 g++, 得安装。如果不联网就只能去麒麟仓库手动下了。还一个问题是 cmake 版本低，这个问题也是通过 cmake 官网下，然后设置环境变量

**Comment by FlyInWind1** [comment]
你们的系统是银河麒麟v10吗，gcc版本是7吗？

**Comment by sandywalker** [comment]
v10(sp1) gcc 版本是 9.3

**Comment by sandywalker** [comment]
> 你们的系统是银河麒麟v10吗，gcc版本是7吗？

我忘了初始 gcc 版本了，应该是后来升级过。

**Comment by TuWei1992** [comment]
> > 你们的系统是银河麒麟v10吗，gcc版本是7吗？
> 
> 我忘了初始 gcc 版本了，应该是后来升级过。

能否分享一下 打好的 so? 谢谢

**Comment by MyMonsterCat** [comment]
感谢使用，您直接提交PR即可
