### ISSUE TITLE
请问为什么ONNX_PPOCR_V4_SERVER被注释了

### ISSUE THREAD

**Issue by nuclear06** [MyMonsterCat/RapidOcr-Java#46]
在commit 2a8ecdd中，模型[ONNX_PPOCR_V4_SERVER被注释](https://github.com/MyMonsterCat/RapidOcr-Java/blob/692d8252857a193e5e4318a3b09ddf2db18a2a43/rapidocr-common/src/main/java/io/github/mymonstercat/Model.java#L14)了，我并没有看到有关此项改变的日志说明，请问是什么原因？

**Comment by MyMonsterCat** [comment]
文件太大了，而且是服务器版本的。如果你想使用该服务器版本，前往下面地址下载替换，然后重新编译打包。
模型文件地址：https://huggingface.co/SWHL/RapidOCR/tree/main/PP-OCRv4
替换路径和这个readme同级：https://github.com/MyMonsterCat/RapidOcr-Java/blob/692d8252857a193e5e4318a3b09ddf2db18a2a43/rapidocr-onnx-models/src/main/resources/models/readme.md

**Comment by MyMonsterCat** [comment]
文件太大了，而且是服务器版本的，一般用不到。如果你想使用该服务器版本，前往下面地址下载加入，然后重新编译打包。
模型文件地址：https://huggingface.co/SWHL/RapidOCR/tree/main/PP-OCRv4
加入路径和这个readme同级：https://github.com/MyMonsterCat/RapidOcr-Java/blob/692d8252857a193e5e4318a3b09ddf2db18a2a43/rapidocr-onnx-models/src/main/resources/models/readme.md
