### ISSUE TITLE
如何是用paddleocr中的文本方向识别功能

### ISSUE THREAD

**Issue by 204winnersong** [MyMonsterCat/RapidOcr-Java#48]
如标题：如何是用paddleocr中的文本方向识别功能？

**Comment by MyMonsterCat** [comment]
<img width="964" alt="image" src="https://github.com/MyMonsterCat/RapidOcr-Java/assets/33886291/fd81017a-5922-4247-b3ec-af03a0aec911">
试试这个能满足你需求不
