### ISSUE TITLE
如何让 RapidOcr-Java 返回角度数字int类型的

### ISSUE THREAD

**Issue by 204winnersong** [MyMonsterCat/RapidOcr-Java#49]
如上题目：
如何让 RapidOcr-Java 返回角度数字int类型的？？

**Comment by MyMonsterCat** [comment]
咱不支持，项目jni调用的是这个项目[RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx)，如果要返回你需要的，需要从这个项目入手。
