### ISSUE TITLE
如果有一个onnx文件，是rapid_orientation.onnx，如何实现用java调用，甚至说打包成咱们这个项目中。

### ISSUE THREAD

**Issue by 204winnersong** [MyMonsterCat/RapidOcr-Java#50]
如果有一个onnx文件，是rapid_orientation.onnx，如何实现用java调用，甚至说打包成咱们这个项目中。

**Comment by MyMonsterCat** [comment]
参考项目README文件中的Q3:如何使用其他版本(如服务器版本)的模型？

- 拉取本项目最新代码到本地
- 在[该路径下](https://github.com/MyMonsterCat/RapidOcr-Java/tree/main/rapidocr-onnx-models/src/main/resources/models)放入模型文件
- 模型中添加对应的[配置](https://github.com/MyMonsterCat/RapidOcr-Java/blob/main/rapidocr-common/src/main/java/io/github/mymonstercat/Model.java)
- 项目执行打包命令


PS：可以从InferenceEngine类中runOcr往下点点，看一下调用逻辑

**Comment by 204winnersong** [comment]
谢谢大牛的热心指导~

**Comment by 204winnersong** [comment]
大咖，请问一下，这个“ppocr_keys_v1.txt”文件是起什么作用的？

**Comment by MyMonsterCat** [comment]
中文字符集，在PaddleOCR项目中：https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/ppocr_keys_v1.txt

**Comment by 204winnersong** [comment]
那明白了，谢谢您热情的讲解~

**Comment by MyMonsterCat** [comment]
不客气 感谢使用
