### ISSUE TITLE
linux arm64版本问题，找不到包

### ISSUE THREAD

**Issue by GinSmile** [MyMonsterCat/RapidOcr-Java#53]
请问下，我用mvn编译的时候提示maven库没有这个包，是否要自己编译此版本的jar

Failure to find io.github.mymonstercat:rapidocr-onnx-linux-arm64:jar:1.2.2

![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/3349829/35da33d2-2df6-4ec4-a13f-b056600516c8)

**Comment by MyMonsterCat** [comment]
拉取项目代码，找到[rapidocr-onnx-linux-arm64](https://github.com/MyMonsterCat/RapidOcr-Java/tree/main/rapidocr-onnx-linux-arm64)，自行打包即可。

PS：在中央仓库或者中央仓库找不到是因为发布0.0.7版本的时候还没有加linux-arm64，后面加了以后，没有发布0.0.8版本。

**Comment by GinSmile** [comment]
自行编译后就找到了，感谢作者！
