### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by shuhuicoder** [MyMonsterCat/RapidOcr-Java#54]
你好，
我在Linux服务器中报如下异常：
/tmp/ocrJava/onnx/libRapidOcr.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/ocrJava/onnx/libRapidOcr.so)
请问应该如何解决呢？
感谢！

**Comment by GinSmile** [comment]
这个是glibc版本问题吧。你系统的glibc版本太低了，应该升级到2.27版本以后的。

**Comment by MyMonsterCat** [comment]
文档中有写

**Comment by shuhuicoder** [comment]
> 文档中有写

是的，已关注到文档，问题已经解决，再次感谢

**Comment by shuhuicoder** [comment]
> 这个是glibc版本问题吧。你系统的glibc版本太低了，应该升级到2.27版本以后的。

是的，升级版本后问题已解决
