### ISSUE TITLE
下次版本更新model模型的存放路径能否加载时指定绝对路径加载?

### ISSUE THREAD

**Issue by wxy5001** [MyMonsterCat/RapidOcr-Java#55]
现在的onnx的model的路径根据enum写死了的，InferenceEngine.getInstance(Model.ONNX_EN_DIY_V4)
的InferenceEngine类也不能继承重写getInstance方法，对于经常更换模型使用的情况来说，每次都去替换onnx的model文件觉得有点麻烦，能否增加一个InferenceEngine.getInstance("model-dir",mod-name,key-text)类似的方法来初始化，让用户可以直接指定模型存放路径来初始化这个InferenceEngine类，谢谢。

**Comment by MyMonsterCat** [comment]
感谢使用，下次更新安排
