### ISSUE TITLE
更换模型时，作者的最后一句话没有找到修改地方：修改PathConstants.MODEL_REC_NAME为你模型的名称

### ISSUE THREAD

**Issue by GinSmile** [MyMonsterCat/RapidOcr-Java#58]
这个PathConstants.MODEL_REC_NAME在哪里？

**Comment by wxy5001** [comment]
没有这个类的，可能是以前版本的功能吧，我也还没有找到自定义自已模型文件的办法，如果你找到了的话，上来说一下吧，谢谢。

**Comment by MyMonsterCat** [comment]
不好意思，确实是以前版本的功能，升级时文档没有作出修改。现在在这里配置https://github.com/MyMonsterCat/RapidOcr-Java/blob/main/rapidocr-common/src/main/java/io/github/mymonstercat/Model.java
