### ISSUE TITLE
docker容器部署的。请问一下这个问题怎么办呀，不是很明白

### ISSUE THREAD

**Issue by gyf329** [MyMonsterCat/RapidOcr-Java#59]
![捕获](https://github.com/MyMonsterCat/RapidOcr-Java/assets/78125223/0c2e71cf-18e8-465e-ab55-3299228ab5e3)
![FinalShell 4 0 1 2024_6_16 21_04_39](https://github.com/MyMonsterCat/RapidOcr-Java/assets/78125223/fcc39e3a-970f-400e-bd23-19b01f1d3150)

**Comment by gyf329** [comment]
打包命令：mvn clean package -P linux-x86_64 -Dlinux-build

**Comment by MyMonsterCat** [comment]
环境问题，看一下文档，有升级指南
