### ISSUE TITLE
可否将 dll , so 还有 onnx 文件分别打包进jar，上传到maven仓库

### ISSUE THREAD

**Issue by FlyInWind1** [MyMonsterCat/RapidOcr-Java#6]
每个平台一个jar包，例如 io.github.mymonstercat:rapidocr:0.0.4-windows-x64.jar io.github.mymonstercat:rapidocr:0.0.4-linux-x64.jar 
javacv就是这样做的。

**Comment by MyMonsterCat** [comment]
你好，已经打包了的，文档中有写：
![image](https://github.com/MyMonsterCat/RapidOcr-Java/assets/33886291/a95a06f5-9b1c-4f17-abb7-0bc251aad7d8)
如果下载慢，可以去这里下载https://repo1.maven.org/maven2/io/github/mymonstercat/rapidocr/

**Comment by MyMonsterCat** [comment]
或者您的意思是将onnx的库文件打包，rapidocr-onnx这种吗？

**Comment by FlyInWind1** [comment]
![1700097865596](https://github.com/MyMonsterCat/RapidOcr-Java/assets/29172747/e7776d8f-bdc5-4bc3-875a-daee4f538905)

**Comment by FlyInWind1** [comment]
> 或者您的意思是将onnx的库文件打包，rapidocr-onnx这种吗？

是的 onnx 也需要单独打一个jar包

**Comment by FlyInWind1** [comment]
感谢打包。不过，我刚刚在尝试的时候，发现maven.compiler.target是17，可否换成1.8。原因大家都懂。。

**Comment by MyMonsterCat** [comment]
将代码拉下来，改成1.8，在父项目 执行clean、install...等操作，暂时打包到本地用吧。
中央仓库的jar没办法覆盖，只能升级(つ﹏<。)，compiler1.8会和新功能下个版本一起发布。
